### ISSUE TITLE
项目里的很多链接挂掉了

### ISSUE THREAD

**Issue by phy25** [ihacklog/hacklog-remote-attachment-upyun#25]
http://ihacklog.com/php/wordpress/plugins/hacklog-remote-attachment-upaiyun-version.html

http://ihacklog.com/donate

http://github.ihacklog.com/hacklog-remote-attachment-upyun/

**Comment by ihacklog** [comment]
修改了，新链接： http://ihacklog.com/hacklog-remote-attachment-upaiyun-version.html
